### ISSUE TITLE
Planters and trowel missing

### ISSUE THREAD

**Issue by LocoMinerDad** [jaquadro/GardenStuff#5]
Minecraft v 1.12
forge 1.2443
mod v 2.1.0

I can't find the half the garden stuff in jei.  I dont know the recipes to try to see if its still the game.
Did you take it out?

**Comment by Lethann** [comment]
I know this is an old post but I'm having the same issue.

MC 1.12.2
Forge 14.23.2.2613
GardenStuff 2.1.1

This is a custom modpack I put together though the Twitch client, so no tweeks or anything. Also, I checked the configs folder and there isn't a config for garden stuff. Saw the notice about not everything being in the 1.12 version, but all that's there for me is the fences, lattices, and other stuff pertaining to iron decorative stuff.

**Comment by Lethann** [comment]
Ok from digging around It seems that the iron stuff is the only things in atm? If so you might want to put that info on your mod description so people know. Just saying "not fully implemented" doesn't tell the users enough. One would reasonably expect a few of the core things to be there, ie the gardening stuff. That's why I downloaded this mod. With that not in I'll just put it on my favs list and wait for yall to update it some more.

No rush or anything, just in your own time.
